version: '3.9'
services:
  frontend:
    build: 
      context: ./
    container_name: agrotemplate
    ports:
      - "4242:4242"
    networks:
      - agrotemplate-network
networks:
  agrotemplate-network:
    driver: bridge