import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import FooterComponent from '@/components/common/FooterComponent'
import NavbarComponent from '@/components/common/NavbarComponent'
import { Providers } from './providers'
import { DataContextProvider } from '@/context/catalog-context/CatalogContext'
import { CartProvider } from '@/context/cart-context/cart-context'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" >
      <body className={`${inter.className} bg-body`}> 
      <DataContextProvider>
        <Providers>
          <CartProvider>
            <NavbarComponent/>
              {children}
            <FooterComponent/>
          </CartProvider>
        </Providers>
      </DataContextProvider>
      </body>
    </html>
  )
}
